%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/rop/data-minig/project02-svm/data/training.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/03/26 19:31:06

%% Initialize variables.
filename = '/home/rop/data-minig/project02-svm/data/training.txt';
delimiter = ' ';
endRow = 1000;


training = importfile(filename,1,10000);
s = svd(training);
plot(s);
%pause;